### ISSUE TITLE
Detection of mutation/fusion genes

### ISSUE THREAD

**Issue by EduardoGCCM** [nanoporetech/sockeye#10]
Hi!
First, many thanks for developing this tool. It is easy to use and so far I am getting very similar results from the ONT data analysed with Sockeye and technical replicates sequenced with Illumina and analysed with Cellranger (10X Genomics 5' libraries).

I was wondering if you are considering adding support for the detection of mutations (e.g. SNPs) and/or fusion genes. Is there any other tool you would recommend to use where I could use sockeye outputs as inputs (so I could still maintain the single-cell resolution)?

Thank you again!

Best,
Eduardo

**Comment by jbeaulaurier** [comment]
Hi Eduardo,

Apologies for the delayed reply. I'm very pleased to hear that the pipeline is working well for you. Regarding fusion gene detection and other downstream analyses, we have plans to eventually loop that into the workflow, but I don't have a timeline for when that will be implemented. And unfortunately I don't have any tool recommendations for you. Hopefully you've come across some options since you posted this.

Best,
John
