### ISSUE TITLE
Empty UMAP gene plots

### ISSUE THREAD

**Issue by rb520826** [nanoporetech/sockeye#12]
Thank you for making this bioinformatic pipeline!
I am wondering if you can advise why my UMAP gene plots are empty? I have data in my UMAP total and in the gene_expression.processed.tsv file. I have also tried lowering the limits in the config file for matrix_min_genes etc.
Any advice would be appreciated! 
Rosie

**Comment by jbeaulaurier** [comment]
Hi Rosie,

This happens when the gene specified for UMAP plotting cannot be found in the gene expression matrix. This can be for a couple reasons: (1) the gene symbol is not contained in the annotations (check to see if an alternative gene symbol is used instead), or (2) no demultiplexed aligned reads were found for that gene (this can be checked in the sorted BAM file or in IGV).

Please let me know if that doesn't answer your question.

Thanks,
John

**Comment by rb520826** [comment]
Hi John, 

Thank you for getting back so quickly. Issue fixed using reason 1. I'm looking at mouse genes so realised when I looked back at the gene expression .tsv that the gene in the config file should be Tmem212 and not TMEM212 (for example). 

Thank you again!
BW, Rosie

**Comment by wdecoster** [comment]
Maybe adding a .upper() for gene names wouldn't be a terrible idea there?

**Comment by jbeaulaurier** [comment]
Good idea Wouter, just added that fix and push to `master`.
